apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inference-perf-dataset
  labels:
    app: inference-perf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
